./splitTo5Fold.py bag.svm
./splitTo5Fold.py glass.svm
./splitTo5Fold.py handHold.svm
./splitTo5Fold.py hoodies.svm
./splitTo5Fold.py longHair.svm
./splitTo5Fold.py longSleeve.svm
./splitTo5Fold.py noSleeve.svm
./splitTo5Fold.py otherC.svm
./splitTo5Fold.py othersCate.svm
./splitTo5Fold.py outerwear.svm
./splitTo5Fold.py roundShape.svm
./splitTo5Fold.py shirt.svm
./splitTo5Fold.py shortHair.svm
./splitTo5Fold.py shortSleeve.svm
./splitTo5Fold.py sweater.svm
./splitTo5Fold.py tShirt.svm
./splitTo5Fold.py tankTop.svm
./splitTo5Fold.py vShape.svm
