./countTagNum.py bag.svm
./countTagNum.py glass.svm
./countTagNum.py handHold.svm
./countTagNum.py hoodies.svm
./countTagNum.py longHair.svm
./countTagNum.py longSleeve.svm
./countTagNum.py noSleeve.svm
./countTagNum.py otherC.svm
./countTagNum.py othersCate.svm
./countTagNum.py outerwear.svm
./countTagNum.py roundShape.svm
./countTagNum.py shirt.svm
./countTagNum.py shortHair.svm
./countTagNum.py shortSleeve.svm
./countTagNum.py sweater.svm
./countTagNum.py tShirt.svm
./countTagNum.py tankTop.svm
./countTagNum.py vShape.svm
